version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: manager

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080